#!/usr/bin/env bash
#
# Render the izbori2026 voter guide and graft it into an already-built Jekyll
# site at /politika/analiza-izbora/.
#
# The guide is a self-contained static site generated by render.py. Every link
# and asset reference it emits is relative, so the whole dist/ tree can be
# mounted under any path without rewriting.
#
# Usage: build-analiza-izbora.sh <izbori2026-checkout> <built-jekyll-site>
#   SITE_URL  canonical site origin, used for the section sitemap
#             (default: https://muhamed.at)
#
set -euo pipefail

SRC="${1:?path to the izbori2026 checkout}"
SITE="${2:?path to the built Jekyll site (files/_site)}"
MOUNT="politika/analiza-izbora"
BASE_URL="${SITE_URL:-https://muhamed.at}"

[ -f "$SRC/render.py" ] || { echo "no render.py in $SRC" >&2; exit 1; }
[ -d "$SITE" ] || { echo "no built site at $SITE" >&2; exit 1; }

python3 -m pip install --quiet --disable-pip-version-check -r "$SRC/requirements.txt"
( cd "$SRC" && python3 render.py )

DEST="$SITE/$MOUNT"
rm -rf "$DEST"
mkdir -p "$DEST"
cp -R "$SRC/dist/." "$DEST/"

# jekyll-sitemap only indexes pages Jekyll itself built, so the guide needs its
# own sitemap. robots.txt points crawlers at it.
python3 - "$DEST" "$BASE_URL/$MOUNT" <<'PY'
import datetime, os, sys
from xml.sax.saxutils import escape

dest, base = sys.argv[1], sys.argv[2].rstrip("/")
today = datetime.date.today().isoformat()
pages = sorted(f for f in os.listdir(dest) if f.endswith(".html"))

def loc(name):
    return base + "/" + ("" if name == "index.html" else name)

out = ['<?xml version="1.0" encoding="UTF-8"?>',
       '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
for page in pages:
    out.append(f"  <url><loc>{escape(loc(page))}</loc><lastmod>{today}</lastmod></url>")
out.append("</urlset>")

with open(os.path.join(dest, "sitemap.xml"), "w", encoding="utf-8") as fh:
    fh.write("\n".join(out) + "\n")
print(f"sitemap.xml: {len(pages)} pages")
PY

echo "mounted $(find "$DEST" -type f | wc -l) files at /$MOUNT/"
